apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: devfile-sample-go-basic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic
    spec:
      containers:
      - env:
        - name: MY_ENV_VAR
          value: myValue
        image: quay.io/redhat-user-workloads/japower-tenant/devfile-sample-go-basic/devfile-sample-go-basic@sha256:a1fcad9ddf973a4e1bf2852d0fa1dade00624d8b567d9b5fdb7a632eee26f695
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
